### ISSUE TITLE
Publish extension on Open VSX

### ISSUE THREAD

**Issue by trymeouteh** [perlick/markdown-preview-editor#13]
https://open-vsx.org/

Please publish this extension on Open VSX. Open VSX is an extension repository which is used to install extension in VSCodium, an fully open source version of VS Code.

https://vscodium.com/

**Comment by perlick** [comment]
Thanks for bringing this to my attention. I’ll take a look at this in the next few days.

**Comment by perlick** [comment]
@trymeouteh Markdown Preview Editor has been published to Open VSX https://open-vsx.org/extension/MattPerlick/markdown-preview-editor
